title: Dinggao Liu's Homepage
page-top-title: Dinggao Liu's Homepage
# top-section-bg-text: Computer Science
home-subtitle: Dinggao Liu&ensp;|&ensp;刘定杲
copyright-text: '&copy; Dinggao Liu 2025-2026. All Rights Reserved.'
